### ISSUE TITLE
pickle UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 19: ordinal not in range(128)

### ISSUE THREAD

**Issue by tryerrorman** [paulbertens/rank-ordered-autoencoder#1]
I am using python 3.5.1. I download the dataset from the official website: http://www.cs.toronto.edu/~kriz/cifar.html. And the md5 was checked.
the code is the same as yours. But it occured to the UnicodeDecodeError
 dict = pickle.load(fo)
UnicodeDecodeError: 'ascii' codec can't decode byte 0x82 in position 19: ordinal not in range(128)

thank for your time

**Comment by paulbertens** [comment]
The code was only tested on python 2.7 (and 64 bit and windows), this likely has to do with unpickle in python3 of a python2 pickled object. try change it to: dict = pickle.load(fo, encoding='latin-1')

**Comment by tryerrorman** [comment]
Thank you. 
 I have fixed the problem and successfully run it.
